"""Standalone regression coverage for ITensor v3's native KPM energy
truncation (Chain::kpm_energy_truncate/scaled_hamiltonian_gs_anchored in
mpscpp3/chain_session.h, Holzner et al., PRB 83, 195115 (2011),
Sec. III-B) -- the C++ v3 counterpart of pyitensor's energy_truncate(),
implemented as a wholly independent method: kpm_dynamical_correlator(),
kpm_moments_full()/kpm_moments_accelerated(), and scaled_hamiltonian()
are untouched (see chain_session.h's own comment on the new methods).

See test_kpm_energy_truncation.py for the equivalent pyitensor-backend
coverage, and test_kpm_energy_truncation_v3_accuracy.py for end-to-end
coverage through get_dynamical_correlator(submode="KPM").

Uses session.random_mps() rather than a seeded numpy draw: v3's random
state is generated by ITensor's own C++ RNG, not Python's, so
np.random.seed() has no effect on it -- assertions below are
deliberately loose (qualitative, not tied to a specific numeric value)
so they hold regardless of the actual random draw.
"""
import pytest

from dmrgpy import cppext, spinchain

pytestmark = pytest.mark.skipif(
    not cppext.available(3), reason="requires the compiled mpscpp3 (ITensor v3) extension")


def _heisenberg_chain(n=6):
    spins = ["S=1/2" for _ in range(n)]
    sc = spinchain.Spin_Chain(spins)
    sc.setup_cpp(3)
    h = 0
    for i in range(n - 1):
        h = h + sc.Sx[i] * sc.Sx[i + 1] + sc.Sy[i] * sc.Sy[i + 1] + sc.Sz[i] * sc.Sz[i + 1]
    sc.set_hamiltonian(h)
    sc.get_gs()
    return sc


def test_kpm_energy_truncate_noop_when_window_covers_full_spectrum():
    """kpm_scale=1.0 in the ground-state-anchored convention covers
    (E0, E0+W) ~ the whole excitation spectrum, so a generic (random)
    state should already sit inside the window with essentially nothing
    to truncate."""
    sc = _heisenberg_chain(6)
    session = sc._session
    scaled_H, emin, emax, scale = session.scaled_hamiltonian_gs_anchored(1.0)
    psi = session.random_mps()
    new_psi, avg_w, dchange = session.kpm_energy_truncate(psi, scaled_H, 10, 2, 1.0)
    assert avg_w < 1e-6
    assert dchange < 1e-8


def test_kpm_energy_truncate_removes_high_energy_weight():
    """A narrow window (kpm_scale=0.1, i.e. Ws=0.1*(emax-emin) above E0)
    covers only a small fraction of the spectrum, so a generic (random)
    state -- which has support spread across the whole spectrum -- must
    have substantial weight above threshold, and truncating it must
    change it substantially. Re-truncating the already-truncated result
    should then leave it (nearly) unchanged, i.e. converge to a fixed
    point rather than keep drifting."""
    sc = _heisenberg_chain(6)
    session = sc._session
    scaled_H, emin, emax, scale = session.scaled_hamiltonian_gs_anchored(0.1)
    psi = session.random_mps()

    psi1, avg_w1, dchange1 = session.kpm_energy_truncate(psi, scaled_H, 30, 10, 1.0)
    assert dchange1 > 1e-3  # truncation actually did something

    psi2, avg_w2, dchange2 = session.kpm_energy_truncate(psi1, scaled_H, 30, 10, 1.0)
    assert dchange2 < 1e-2 * dchange1  # bulk of the work was the first call


def test_scaled_hamiltonian_gs_anchored_pins_ground_state():
    """Direct check of Eq. (21b)'s defining property: the ground state
    itself is pinned at -(1-safety/2) *by construction*, for any
    kpm_scale -- only the window's upper edge, E0+Ws, moves with
    kpm_scale. So truncating the (exact, already-converged) ground state
    itself must be a no-op regardless of how narrow the window is,
    unlike a generic state (previous test), which does need real
    truncation once the window is narrow."""
    sc = _heisenberg_chain(6)
    session = sc._session
    wf0 = session.gs_wavefunction()
    for kpm_scale in (0.05, 0.1, 0.3, 1.0):
        scaled_H, emin, emax, scale = session.scaled_hamiltonian_gs_anchored(kpm_scale)
        _, avg_w, dchange = session.kpm_energy_truncate(wf0, scaled_H, 10, 3, 1.0)
        assert avg_w < 1e-8
        assert dchange < 1e-10
